// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEzUh_wRr2L8ipNH7cUqfzU6Xv6ce3PIQ',
    appId: '1:549200382896:web:6b8907ff556f18f364a475',
    messagingSenderId: '549200382896',
    projectId: 'on-app-tcc',
    authDomain: 'on-app-tcc.firebaseapp.com',
    storageBucket: 'on-app-tcc.appspot.com',
    measurementId: 'G-WN5P0XYYX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw5-Lcp6OM84lDB2gJovuvFNPXrnyD25Y',
    appId: '1:549200382896:android:98aba49f19ce5df764a475',
    messagingSenderId: '549200382896',
    projectId: 'on-app-tcc',
    storageBucket: 'on-app-tcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArBTbbYWnDtTGfE81zTC3g2kXyKtpDML0',
    appId: '1:549200382896:ios:28cf9cb8f8b204b464a475',
    messagingSenderId: '549200382896',
    projectId: 'on-app-tcc',
    storageBucket: 'on-app-tcc.appspot.com',
    iosClientId: '549200382896-11deoqanq5skuj123vr0v781m4tfn28d.apps.googleusercontent.com',
    iosBundleId: 'com.on.entreprise.onMobile',
  );
}
